# This is a basic workflow to help you get started with Actions

name: Build AppImage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  AppImage:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}
    - name: Download dependencies
      run: |
        sudo apt-get -y install libdbus-glib-1-dev
        
        sudo apt install libxkbcommon0 libxcb-xkb-dev libxkbcommon-x11-0 libxcb-xkb1
        
    - name: Test AppImage
      run: |
        python -m pip install python-appimage dbus-python
        python -m python_appimage build app appimage \
                                            --linux-tag=manylinux1_x86_64
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: swaglyrics-continuous-x86_64.AppImage
        path: swaglyrics-x86_64.AppImage

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Continuous"
        files: |
          swaglyrics-x86_64.AppImage
